import type { monthlyReport } from '@/types/monthlyReport';

const monthlyReportItems: monthlyReport[] = [
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '０１２３４５６７８９',
    department: 'WT',
    status: '作成中',
    subscription: 8100,
    trafficCost: 21620,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: false,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名氏名氏名',
    department: 'WT',
    status: '承認済み',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:26',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customerfalse',
    approval: false
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認済み',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: false
  },
  {
    name: '０１２３４５６７８９',
    department: 'WT',
    status: '承認済み',
    subscription: 8100,
    trafficCost: 21620,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: false,
    customerWorkSchedule: 'done',
    approval: false
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: false
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認依頼',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '０１２３４５６７８９',
    department: 'WT',
    status: '作成中',
    subscription: 8100,
    trafficCost: 21620,
    monthlyReportUpdate: '05/30 15:15',
    otherCheck: true,
    companyWorkSchedule: false,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名2',
    department: 'GW',
    status: '差戻し中',
    subscription: 11500,
    trafficCost: 1800,
    monthlyReportUpdate: '05/30 15:16',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'done',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認済み',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  },
  {
    name: '社員氏名1',
    department: 'GW',
    status: '承認済み',
    subscription: 8100,
    trafficCost: 620,
    monthlyReportUpdate: '05/30 15:25',
    otherCheck: true,
    companyWorkSchedule: true,
    customerWorkSchedule: 'customertrue',
    approval: true
  }
];

export default monthlyReportItems;
